server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cliente-persona-service
          uri: lb://cliente-persona-service
          predicates:
            - Path=/api/clientes/**
        - id: cuenta-movimiento-service
          uri: lb://cuenta-movimiento-service
          predicates:
            - Path=/api/cuentas/**,/api/movimientos/**,/api/reportes/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
